# name: Generate Snake Animation

# on:
#   schedule: # Executes every 12 hours
#     - cron: "0 */12 * * *" # Adjusted for better clarity (midnight and noon UTC)

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v3
#         with:
#           cache: yarn
#           node-version: 20
#       - run: yarn install --frozen-lockfile

#       - run: npm run type
#       - run: npm run lint
#       - run: npm run test --ci
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#   generate-snake:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Generate Snake Animation
#         id: generate-snake
#         uses: Platane/snk@master
#         with:
#           github_user_name: hasithz # Update with your GitHub username
#           outputs: |
#             dist/github-contribution-grid-snake.svg
#             dist/github-contribution-grid-snake-dark.svg?palette=github-dark
#             dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#       - name: Ensure Files Exist
#         run: |
#           ls dist
#           test -f dist/github-contribution-grid-snake.svg
#           test -f dist/github-contribution-grid-snake-dark.svg
#           test -f dist/github-contribution-grid-snake.gif

#       - name: Deploy to GitHub Pages
#         uses: crazy-max/ghaction-github-pages@v3.1.0
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#   deploy-demo:
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v3
#         with:
#           cache: yarn
#           node-version: 20
#       - run: yarn install --frozen-lockfile

#       - name: Build Demo
#         run: npm run build:demo
#         env:
#           GITHUB_USER_CONTRIBUTION_API_ENDPOINT: https://snk-one.vercel.app/api/github-user-contribution/

#       - name: Deploy Demo to GitHub Pages
#         uses: crazy-max/ghaction-github-pages@v3.1.0
#         with:
#           target_branch: gh-pages
#           build_dir: packages/demo/dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN_GH_PAGES }}
